#!/bin/bash

# Ask for input file
echo "Enter file name:"
read filename

# Loop through each line in file
while read -r line
do
  # Get first character of line and add to decoded string
  decoded="${decoded}${line:0:1}"
done < "$filename"

# Output decoded string with new line at the end
echo -e "${decoded}\n"
