#!/bin/bash

echo "Local variables:"
declare -p | awk -F= '/declare --/ {print "\t"$1}'
echo "Environment variables:"
env | awk -F= '{print "\t"$1}'
echo "Functions:"
declare -F | awk '{print "\t"$3}'
