#!/bin/bash

echo "Variables locales :"
set | grep '^[a-zA-Z_][a-zA-Z0-9_]*=' | sed 's/=.*//'

echo "Variables d'environnement :"
set | grep -v '^[a-zA-Z_][a-zA-Z0-9_]*=' | grep -v '^\(BASH\|PROMPT\|SHLVL\|TERM\|OLDPWD\|PWD\|_\)\='

echo "Fonctions :"
declare -F | awk '{print $NF}'

